

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile  
    environment:
      PORT: 8080
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:toma@db:5432/prisma_1
      JWT_ACCESS_TOKEN_SECRET: access_secret_key
      JTW_REFRESH_TOKEN_SECRET: refresh_secret_key
      JWT_ACCESS_TOKEN_EXPIRES_AT: 5m
      JWT_REFRESH_TOKEN_EXPIRES_AT: 24h
    depends_on:
      - db 
    ports:
      - "8080:8080"
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: toma 
      POSTGRES_USER: postgres
      POSTGRES_DB: prisma_1
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql 

volumes:
  db-data:
